### PR TITLE
Update strings for zh-Hant

### PR DESCRIPTION
**Pull request by andy0130tw**
I improved the localization strings for zh-Hant to be more familiar and consistent to Facebook users in Taiwan. Notably the following terms:

* feed -> 動態消息
* post -> 貼文
* short video -> 短影片
* Paid partnership -> 付費合作
* information box -> 資訊框

### CODE REVIEW

**Comment by zbluebugz** [comment]
Thanks for the update. Muchly appreciated.

Merging the changes and will copy the updates into the offline development copy.

**Comment by zbluebugz** [comment]
Could you give me a translation for "Events you may like", please? Will be adding an option to hide this.

This appears in the main News Feed for some people.

**Comment by andy0130tw** [comment]
I haven't noticed such a section like that today, but it is titled "你可能感興趣的活動" if my memory serves.

**Comment by zbluebugz** [comment]
Thanks - doesn't show up very often.

**Pull request merged**
